
name: Deploy to EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DRUPAL_EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa    
          ssh-keyscan 52.70.109.97 >> /home/runner/.ssh/known_hosts
          cat '/home/runner/.ssh/known_hosts'
          echo "end of ssh key setup"
      - name: Connect to EC2 and Copy Files
        run: |
          ssh -vvv -o StrictHostKeyChecking=no root@52.70.109.97 "mkdir -p /var/www/html"
          ssh -vvv -o StrictHostKeyChecking=no root@52.70.109.97 "cd /var/www/html && rm -rf * && git init && git clone https://github.com/sairevanthreddy/drupal.git"
          ssh -vvv -o StrictHostKeyChecking=no root@52.70.109.97 "cp /var/settings.php /var/www/html/drupal/sites/default"
